# Generated by Django 4.1 on 2025-05-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together=set(),
        ),
    ]
